---
- block:
  - name: add elasticsearch apt key
    apt_key:
      url: https://packages.elastic.co/GPG-KEY-elasticsearch
      state: present
      validate_certs: yes
      id: D88E42B4

  - name: add elasticsearch repository
    apt_repository:
      repo: 'deb http://packages.elastic.co/elasticsearch/2.x/debian stable main'
      state: present
      update_cache: yes
      validate_certs: yes

  - name: install elasticsearch
    apt:
      cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
      name: elasticsearch
      state: present
      install_recommends: no
      update_cache: yes

  - name: copy elasticsearch config
    template:
      src: elasticsearch.yml.j2
      dest: "{{ elasticsearch_conf_dir }}/elasticsearch.yml"
      owner: root
      group: elasticsearch
      mode: 0750
      backup: true
    notify: restart elasticsearch

  - name: start elasticsearch & enable at boot
    service:
      name: elasticsearch
      state: started
      enabled: yes
  become: true
  become_method: sudo
  tags:
    - elasticsearch
