---
- hosts: elasticsearch
  vars:
    apt_cache_valid_time: 3600
    elasticsearch_network_bind: 0
  roles:
    - role: elasticsearch

- hosts: kibana
  vars:
    apt_cache_valid_time: 3600
    kibana_elasticsearch_url: "http://192.168.20.20:9200"
  roles:
    - role: kibana-4.4
