---
- hosts: all
  vars:
    apt_cache_valid_time: 3600
  tasks:
    - block:
        - name: ansible user
          user:
            name:    ansible
            comment: Ansible provisioner
            shell:   /bin/bash
            system:  yes
            state:   present

        - name: let ansible have passwordless sudo
          copy:
            dest: /etc/sudoers.d/ansible
            content: "ansible ALL=(ALL:ALL) NOPASSWD: ALL"
            owner: root
            group: root
            mode: 0440

        - name: authorize ansible key
          authorized_key:
            exclusive: yes
            key: "{{ lookup('file', '/etc/ansible/.ssh/id_rsa_ansible.pub') }}"
            user: ansible
      
        - name: apt-get upgrade
          apt:
            cache_valid_time: "{{ apt_cache_valid_time|default(omit) }}"
            update_cache: yes
            upgrade: full

      become: true
      become_method: sudo
